access_account_name = "Salesforce-AWS"
aws_account_id      = "111111111111"
incoming_ssl_cidr   = ["0.0.0.0/0"]
create_iam_roles    = false
ec2_role_name       = "aviatrix-role-ec2"
app_role_name       = "aviatrix-role-app"
keypair             = "SalesforceKeypair"
sfaccess_key        =
sfsecret_key        =
sftoken             = 
